version: '3.8'

services:
  carwash-api:
    image: carwash-api:latest
    build:
      context: ./src/CarWash.Api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: carwash
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: