version: '3.8'

services:
  # (Provavelmente você já tem o serviço da sua API aqui)
  # carwash.api:
  #   image: ${DOCKER_REGISTRY-}carwashapi
  #   build:
  #     context: .
  #     dockerfile: src/CarWash.Api/Dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - postgres-db # Faz a API esperar o banco subir

  # Serviço do Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:15-alpine # Você pode usar uma versão mais recente ou específica
    container_name: carwash_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_segura # <== Use a mesma senha do appsettings.json
      POSTGRES_DB: carwash_db             # <== O nome do banco que o EF vai procurar
    ports:
      - "5432:5432" # Expõe a porta 5432 do container para a porta 5432 da sua máquina
    volumes:
      - postgres-data:/var/lib/postgresql/data # Garante que os dados não sejam perdidos

volumes:
  postgres-data: # Define o volume para persistência